### ISSUE TITLE
Everything streamier

### ISSUE THREAD

**Issue by grncdr** [grncdr/browserify-as-a-service#4]
I've decided to break things down _way_ more and build components out of streams rather than promises. The current modules I have in various states of completion:

`create-dependency-stream` - (packageJson) -> stream of "dependency objects" _more below_
`resolve-dependency-versions` - (registry) -> (stream of dependencies) -> (stream of dependencies with exact versions)
`get-package-jsons` - (registry) -> (stream of dependencies with versions) -> (stream of packageJson objects)

By combining these with some dynamic mux/demux action I think I can create this function:

```
function resolveAllDependencies(name, versionRange) -> stream of dependency objects
```

The dependency objects will look like this:

``` javascript
{
    name: 'package-name',
    versionRange: '2.x',   // whatever was in package.json
    version: '2.4.12'      // the actual version we've resolved
    package: { /* package.json contents */ },
    dependencies: { /* name -> dependency object map of this packages dependencies */ } 
    parent: { /* (optional) reference to the dependency object of the dependency that included this one */}
}
```

Given the fully resolved dependency object we can safely hash it (or any of it's children) and install the packages into a working directory. In fact we can probably hook up a through stream that starts installing packages as soon as any dependency object is fully resolved. I'm thinking this might _also_ make it possible to symlink in dependencies a lot of the time rather than installing them, but that's a little further down the road.

**Comment by max-mapper** [comment]
+1

**Comment by grncdr** [comment]
ok, this all exists and "works" (no tests whatsoever).

My next step is the `prepare-package` part that I mentioned [over on #3](https://github.com/grncdr/browserify-as-a-service/issues/3#issuecomment-19157227), I'm thinking this will listen to the dependency stream and fetch/prepare npm packages.

I need to read more npm source and to see if I can re-use it's cache implementation, but I'm pretty tempted at this point to just write my own implementation that symlinks everything when possible. In particular, the registry already has sha1 hashes in the package.json files it serves, so I could use those to ensure that every unique package exists once-and-only-once. I'm thinking a process like the following (using shell, for some reason):
1. `export cache_dir=${root_cache_dir}/{$sha1:0:2}/${sha1:2:4}/${sha1:4:6}/${sha1:6}`
2. if `$cache_dir` exists, return early.
3. fetch the tarball and unpack it into `$cache_dir`
4. symlink each of it's dependencies from their location in the cache into `${cache_dir}/node_modules`
5. do an `npm install` in `$cache_dir` (maybe this should be a `rebuild` not sure).
6. (Not necessary, but makes things easier to debug) create or update the symlink from `${packages_directory}/${package_name:0:2}/${package_name}/${package_version}` to `${cache_dir}/${hash_dir}`

The existing `create-dependency-stream` code already emits leaf nodes first so there'd (presumably) be no need to even worry about recursively processing dependencies, though it might be nice to run steps 1-3 concurrently for each dependency and then coordinate the start of step 4 so that we know we have all necessary packages before symlinking.

So that's an as-yet-unnamed component that will be used by `browserify-bundle-factory`. Then the API for `browserify-bundle-factory` will be something like this:

``` javascript
var bundleFactory = require('browserify-bundle-factory')(options);

bundleFactory(pkgJSON, browserifyOptions) //=> browserify stream
```

which should be really easy to hook up to any sort of web front-end:

``` javascript
require('http').createServer(function (req, res) {
   // parse body to get pkgJSON and browserifyOptions
   bundleFactory(pkgJSON, browserifyOptions).pipe(res);
})
```

**Comment by grncdr** [comment]
progress notes:

the signature of the returned function is now `bundleFactory(pkgJSON, sources, browserifyOptions)` where `sources` is an object that looks like this:

``` javascript
{
  "./path/to/file.js": {
    source: "// javascript source code",
    options: {
      // addtional options to pass to b.require() such as
      entry: true
    }
  }
}
```
